name: run-testmore
on: 
  push:
  workflow_dispatch:
jobs:
  run-testmore:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install spict
        run: make install
      
      - name: test spict
        run: make testmore
